on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Test our full build first, this will catch any syntax errors right away.
    - run: |
        nix build .
        ./result/bin/squire
