on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Note for tests we disable parallelization because we use Docker
    # and we don't want to create many containers at once.
    - uses: workflow/nix-shell-action@v1
      with:
        script: |
          go test -p 1 ./...
