on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Run our checks to catch quick issues
    # NOTE: we disable this for now because flake-utils isn't setting up the
    # overlay args correctly.
    # - run: nix flake check

    # Test our full build first, this will catch any syntax errors right away.
    - name: build and run
      run: |
        nix build .
        ./result/bin/squire --version

    # Run our go tests within the context of the dev shell from the flake. This
    # will ensure we have all our dependencies.
    - name: test
      run: nix develop -c go test -p 1 ./...
